package com.opensynaptic.gsynjava;

import android.content.Context;
import android.content.SharedPreferences;

import com.opensynaptic.gsynjava.core.AlertNotificationHelper;
import com.opensynaptic.gsynjava.core.protocol.GeohashDecoder;
import com.opensynaptic.gsynjava.data.AppRepository;
import com.opensynaptic.gsynjava.data.Models;
import com.opensynaptic.gsynjava.rules.RulesEngine;
import com.opensynaptic.gsynjava.transport.TransportManager;

public class AppController implements TransportManager.MessageListener {
    private static AppController instance;

    private final Context context;
    private final SharedPreferences preferences;
    private final AppRepository repository;
    private final TransportManager transportManager;
    private final RulesEngine rulesEngine;

    private AppController(Context context) {
        this.context = context.getApplicationContext();
        this.preferences = this.context.getSharedPreferences("gsyn_java_prefs", Context.MODE_PRIVATE);
        this.repository = AppRepository.get(this.context);
        this.transportManager = TransportManager.get(this.context);
        this.rulesEngine = new RulesEngine(repository, transportManager);
        this.transportManager.addMessageListener(this);
        repository.seedDefaultRuleIfEmpty();
        AlertNotificationHelper.createChannels(this.context); // create notification channels once
    }

    public static synchronized AppController get(Context context) {
        if (instance == null) instance = new AppController(context);
        return instance;
    }

    public AppRepository repository() {
        return repository;
    }

    public TransportManager transport() {
        return transportManager;
    }

    public SharedPreferences preferences() {
        return preferences;
    }

    @Override
    public void onMessage(Models.DeviceMessage message) {
        Models.Device device = new Models.Device();
        device.aid = message.deviceAid;
        device.name = message.nodeId == null || message.nodeId.isEmpty() ? "Device " + message.deviceAid : message.nodeId;
        device.status = "online";
        device.transportType = message.transportType;
        device.lastSeenMs = System.currentTimeMillis();

        // Detect GEO sensor readings and decode geohash → lat/lng
        for (Models.SensorReading reading : message.readings) {
            if (GeohashDecoder.isGeoSensor(reading.sensorId)) {
                String hash = reading.rawB62 != null && !reading.rawB62.isEmpty()
                        ? reading.rawB62 : reading.unit;
                double[] latLng = GeohashDecoder.decode(hash);
                if (latLng != null) {
                    device.lat = latLng[0];
                    device.lng = latLng[1];
                }
            }
        }

        repository.upsertDevice(device);

        // Use device timestamp if valid; fall back to system clock
        long sampleMs = (message.timestampSec > 0)
                ? message.timestampSec * 1000L
                : System.currentTimeMillis();

        for (Models.SensorReading reading : message.readings) {
            Models.SensorData data = new Models.SensorData();
            data.deviceAid = message.deviceAid;
            data.sensorId = reading.sensorId;
            data.unit = reading.unit;
            data.value = reading.value;
            data.rawB62 = reading.rawB62;
            data.timestampMs = sampleMs;
            repository.insertSensorData(data);
        }

        String udpHost = preferences.getString("udp_host", "127.0.0.1");
        int udpPort = preferences.getInt("udp_port", 9876);
        rulesEngine.evaluate(message, udpHost, udpPort);

        // Send local push notification for Warning / Critical alerts generated by this message
        notifyNewAlerts(message.deviceAid);
    }

    /**
     * Checks the most-recent unacknowledged alerts for this device and sends a
     * local notification if any Critical or Warning alert was just inserted.
     * We look at the 5 latest unacked alerts to catch the freshest entry.
     */
    private void notifyNewAlerts(int deviceAid) {
        java.util.List<Models.AlertItem> recent = repository.getAlerts(null, 5);
        for (Models.AlertItem alert : recent) {
            if (alert.acknowledged) continue;
            if (alert.deviceAid != deviceAid) continue;
            if (alert.level < 1) continue; // skip Info
            // Only notify for alerts created within the last 5 seconds
            if (System.currentTimeMillis() - alert.createdMs > 5_000L) continue;
            AlertNotificationHelper.notify(context, alert.level, alert.message, alert.deviceAid);
            break; // one notification per incoming packet is enough
        }
    }
}
